#!/usr/bin/env python3
import os
from utils import expand_path
from SHARC_GAUSSIAN import SHARC_GAUSSIAN
import json

PATH = expand_path("$SHARC/../tests/interface")


def test_schedule():
    gaussian = SHARC_GAUSSIAN()
    gaussian.setup_mol(os.path.join(PATH, "inputs/QM7.in"))
    gaussian.QMin.resources["ncpu"] = 1
    gaussian.QMin.resources["memory"] = 2000
    gaussian._read_resources = True
    gaussian._read_template = True
    gaussian.setup_interface()
    gaussian.read_requests(os.path.join(PATH, "inputs/QM7.in"))
    gaussian.set_coords(os.path.join(PATH, "inputs/QM7.in"))
    gaussian.generate_joblist()
    # with open("/user/severin/sharc_main/tests/interface/test_gaussian.py", "a") as f:
    # print("[", file=f)
    # for job in gaussian.QMin.scheduling["schedule"]:
    # print("{", file=f)
    # for key, val in job.items():
    # print(f'"{key}":', "{", file=f)
    # for subk in ["control", "molecule", "resources", "maps"]:
    # print(f'"{subk}": {val[subk].data},', file=f)
    # print("}", file=f)
    # print("},", file=f)
    # print("]", file=f)

    ref_schedule = [
        {
            "master_1": {
                "control": {
                    "jobid": 1,
                    "workdir": None,
                    "master": True,
                    "gradonly": False,
                    "densonly": False,
                    "states_to_do": [3, 0, 2],
                    "jobs": {1: {"mults": [1], "restr": True}, 3: {"mults": [1, 3], "restr": True}},
                    "nslots_pool": [1],
                    "joblist": [1, 3],
                    "njobs": 2,
                    "jobgrad": {
                        (1, 2): ("master_1", False),
                        (3, 1): ("master_3", False),
                        (1, 1): ("grad_1_1", True),
                        (1, 3): ("grad_1_3", False),
                        (3, 2): ("grad_3_2", False),
                    },
                    "densjob": {},
                    "rootstate": 1,
                },
                "molecule": {
                    "comment": "\n",
                    "natom": 3,
                    "elements": ["S", "O", "O"],
                    "unit": "angstrom",
                    "factor": 1.8897261246257702,
                    "states": [3, 0, 2],
                    "nstates": 5,
                    "nmstates": 9,
                    "point_charges": False,
                    "npc": 0,
                    "Atomcharge": 32,
                    "frozcore": 7,
                },
                "resources": {
                    "pwd": os.getcwd(),
                    "cwd": os.getcwd(),
                    "scratchdir": os.path.join(os.getcwd(), "SCRATCH"),
                    "ncpu": 1,
                    "ngpu": None,
                    "memory": 2000,
                    "delay": 0.0,
                    "theodir": None,
                    "theodore_prop": [],
                    "theodore_fragment": [],
                    "wfoverlap": "$SHARC/wfoverlap.x",
                    "wfthres": 0.998,
                    "resp_shells": [],
                    "resp_vdw_radii_symbol": {},
                    "resp_vdw_radii": [],
                    "resp_betas": [0.0005, 0.0015, 0.003],
                    "resp_layers": 4,
                    "resp_first_layer": 1.4,
                    "resp_density": 10.0,
                    "resp_fit_order": 2,
                    "resp_mk_radii": True,
                    "resp_grid": "lebedev",
                    "groot": None,
                    "numfrozcore": 0,
                    "wfnumocc": None,
                    "schedule_scaling": 0.9,
                    "neglected_gradient": "zero",
                    "dry_run": False,
                    "debug": False,
                    "min_cpu": 1,
                },
                "maps": {
                    "statemap": {
                        1: [1, 1, 0.0],
                        2: [1, 2, 0.0],
                        3: [1, 3, 0.0],
                        4: [3, 1, -1.0],
                        5: [3, 2, -1.0],
                        6: [3, 1, 0.0],
                        7: [3, 2, 0.0],
                        8: [3, 1, 1.0],
                        9: [3, 2, 1.0],
                    },
                    "mults": None,
                    "gsmap": {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
                    "gradmap": {(1, 2)},
                    "nacmap": None,
                    "densmap": None,
                    "ionmap": None,
                    "chargemap": {1: 0, 2: 1, 3: 0},
                    "multmap": {1: 1, -1: [1], 3: 3, -3: [1, 3]},
                },
            },
            "master_3": {
                "control": {
                    "jobid": 3,
                    "workdir": None,
                    "master": True,
                    "gradonly": False,
                    "densonly": False,
                    "states_to_do": [1, 0, 2],
                    "jobs": {1: {"mults": [1], "restr": True}, 3: {"mults": [1, 3], "restr": True}},
                    "nslots_pool": [1],
                    "joblist": [1, 3],
                    "njobs": 2,
                    "jobgrad": {
                        (1, 2): ("master_1", False),
                        (3, 1): ("master_3", False),
                        (1, 1): ("grad_1_1", True),
                        (1, 3): ("grad_1_3", False),
                        (3, 2): ("grad_3_2", False),
                    },
                    "densjob": {},
                    "rootstate": 1,
                },
                "molecule": {
                    "comment": "\n",
                    "natom": 3,
                    "elements": ["S", "O", "O"],
                    "unit": "angstrom",
                    "factor": 1.8897261246257702,
                    "states": [1, 0, 2],
                    "nstates": 5,
                    "nmstates": 9,
                    "point_charges": False,
                    "npc": 0,
                    "Atomcharge": 32,
                    "frozcore": 7,
                },
                "resources": {
                    "pwd": os.getcwd(),
                    "cwd": os.getcwd(),
                    "scratchdir": os.path.join(os.getcwd(), "SCRATCH"),
                    "ncpu": 1,
                    "ngpu": None,
                    "memory": 2000,
                    "delay": 0.0,
                    "theodir": None,
                    "theodore_prop": [],
                    "theodore_fragment": [],
                    "wfoverlap": "$SHARC/wfoverlap.x",
                    "wfthres": 0.998,
                    "resp_shells": [],
                    "resp_vdw_radii_symbol": {},
                    "resp_vdw_radii": [],
                    "resp_betas": [0.0005, 0.0015, 0.003],
                    "resp_layers": 4,
                    "resp_first_layer": 1.4,
                    "resp_density": 10.0,
                    "resp_fit_order": 2,
                    "resp_mk_radii": True,
                    "resp_grid": "lebedev",
                    "groot": None,
                    "numfrozcore": 0,
                    "wfnumocc": None,
                    "schedule_scaling": 0.9,
                    "neglected_gradient": "zero",
                    "dry_run": False,
                    "debug": False,
                    "min_cpu": 1,
                },
                "maps": {
                    "statemap": {
                        1: [1, 1, 0.0],
                        2: [1, 2, 0.0],
                        3: [1, 3, 0.0],
                        4: [3, 1, -1.0],
                        5: [3, 2, -1.0],
                        6: [3, 1, 0.0],
                        7: [3, 2, 0.0],
                        8: [3, 1, 1.0],
                        9: [3, 2, 1.0],
                    },
                    "mults": None,
                    "gsmap": {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
                    "gradmap": {(3, 1)},
                    "nacmap": None,
                    "densmap": None,
                    "ionmap": None,
                    "chargemap": {1: 0, 2: 1, 3: 0},
                    "multmap": {1: 1, -1: [1], 3: 3, -3: [1, 3]},
                },
            },
        },
        {
            "grad_1_1": {
                "control": {
                    "jobid": 1,
                    "workdir": None,
                    "master": False,
                    "gradonly": True,
                    "densonly": False,
                    "states_to_do": [3, 0, 2],
                    "jobs": {1: {"mults": [1], "restr": True}, 3: {"mults": [1, 3], "restr": True}},
                    "nslots_pool": [1, 1],
                    "joblist": [1, 3],
                    "njobs": 2,
                    "jobgrad": {
                        (1, 2): ("master_1", False),
                        (3, 1): ("master_3", False),
                        (1, 1): ("grad_1_1", True),
                        (1, 3): ("grad_1_3", False),
                        (3, 2): ("grad_3_2", False),
                    },
                    "densjob": {},
                    "rootstate": 0,
                },
                "molecule": {
                    "comment": "\n",
                    "natom": 3,
                    "elements": ["S", "O", "O"],
                    "unit": "angstrom",
                    "factor": 1.8897261246257702,
                    "states": [3, 0, 2],
                    "nstates": 5,
                    "nmstates": 9,
                    "point_charges": False,
                    "npc": 0,
                    "Atomcharge": 32,
                    "frozcore": 7,
                },
                "resources": {
                    "pwd": os.getcwd(),
                    "cwd": os.getcwd(),
                    "scratchdir": os.path.join(os.getcwd(), "SCRATCH"),
                    "ncpu": 1,
                    "ngpu": None,
                    "memory": 2000,
                    "delay": 0.0,
                    "theodir": None,
                    "theodore_prop": [],
                    "theodore_fragment": [],
                    "wfoverlap": "$SHARC/wfoverlap.x",
                    "wfthres": 0.998,
                    "resp_shells": [],
                    "resp_vdw_radii_symbol": {},
                    "resp_vdw_radii": [],
                    "resp_betas": [0.0005, 0.0015, 0.003],
                    "resp_layers": 4,
                    "resp_first_layer": 1.4,
                    "resp_density": 10.0,
                    "resp_fit_order": 2,
                    "resp_mk_radii": True,
                    "resp_grid": "lebedev",
                    "groot": None,
                    "numfrozcore": 0,
                    "wfnumocc": None,
                    "schedule_scaling": 0.9,
                    "neglected_gradient": "zero",
                    "dry_run": False,
                    "debug": False,
                    "min_cpu": 1,
                },
                "maps": {
                    "statemap": {
                        1: [1, 1, 0.0],
                        2: [1, 2, 0.0],
                        3: [1, 3, 0.0],
                        4: [3, 1, -1.0],
                        5: [3, 2, -1.0],
                        6: [3, 1, 0.0],
                        7: [3, 2, 0.0],
                        8: [3, 1, 1.0],
                        9: [3, 2, 1.0],
                    },
                    "mults": None,
                    "gsmap": {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
                    "gradmap": {(1, 1)},
                    "nacmap": None,
                    "densmap": None,
                    "ionmap": None,
                    "chargemap": {1: 0, 2: 1, 3: 0},
                    "multmap": {1: 1, -1: [1], 3: 3, -3: [1, 3]},
                },
            },
            "grad_1_3": {
                "control": {
                    "jobid": 1,
                    "workdir": None,
                    "master": False,
                    "gradonly": True,
                    "densonly": False,
                    "states_to_do": [3, 0, 2],
                    "jobs": {1: {"mults": [1], "restr": True}, 3: {"mults": [1, 3], "restr": True}},
                    "nslots_pool": [1, 1],
                    "joblist": [1, 3],
                    "njobs": 2,
                    "jobgrad": {
                        (1, 2): ("master_1", False),
                        (3, 1): ("master_3", False),
                        (1, 1): ("grad_1_1", True),
                        (1, 3): ("grad_1_3", False),
                        (3, 2): ("grad_3_2", False),
                    },
                    "densjob": {},
                    "rootstate": 2,
                },
                "molecule": {
                    "comment": "\n",
                    "natom": 3,
                    "elements": ["S", "O", "O"],
                    "unit": "angstrom",
                    "factor": 1.8897261246257702,
                    "states": [3, 0, 2],
                    "nstates": 5,
                    "nmstates": 9,
                    "point_charges": False,
                    "npc": 0,
                    "Atomcharge": 32,
                    "frozcore": 7,
                },
                "resources": {
                    "pwd": os.getcwd(),
                    "cwd": os.getcwd(),
                    "scratchdir": os.path.join(os.getcwd(), "SCRATCH"),
                    "ncpu": 1,
                    "ngpu": None,
                    "memory": 2000,
                    "delay": 0.0,
                    "theodir": None,
                    "theodore_prop": [],
                    "theodore_fragment": [],
                    "wfoverlap": "$SHARC/wfoverlap.x",
                    "wfthres": 0.998,
                    "resp_shells": [],
                    "resp_vdw_radii_symbol": {},
                    "resp_vdw_radii": [],
                    "resp_betas": [0.0005, 0.0015, 0.003],
                    "resp_layers": 4,
                    "resp_first_layer": 1.4,
                    "resp_density": 10.0,
                    "resp_fit_order": 2,
                    "resp_mk_radii": True,
                    "resp_grid": "lebedev",
                    "groot": None,
                    "numfrozcore": 0,
                    "wfnumocc": None,
                    "schedule_scaling": 0.9,
                    "neglected_gradient": "zero",
                    "dry_run": False,
                    "debug": False,
                    "min_cpu": 1,
                },
                "maps": {
                    "statemap": {
                        1: [1, 1, 0.0],
                        2: [1, 2, 0.0],
                        3: [1, 3, 0.0],
                        4: [3, 1, -1.0],
                        5: [3, 2, -1.0],
                        6: [3, 1, 0.0],
                        7: [3, 2, 0.0],
                        8: [3, 1, 1.0],
                        9: [3, 2, 1.0],
                    },
                    "mults": None,
                    "gsmap": {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
                    "gradmap": {(1, 3)},
                    "nacmap": None,
                    "densmap": None,
                    "ionmap": None,
                    "chargemap": {1: 0, 2: 1, 3: 0},
                    "multmap": {1: 1, -1: [1], 3: 3, -3: [1, 3]},
                },
            },
            "grad_3_2": {
                "control": {
                    "jobid": 3,
                    "workdir": None,
                    "master": False,
                    "gradonly": True,
                    "densonly": False,
                    "states_to_do": [3, 0, 2],
                    "jobs": {1: {"mults": [1], "restr": True}, 3: {"mults": [1, 3], "restr": True}},
                    "nslots_pool": [1, 1],
                    "joblist": [1, 3],
                    "njobs": 2,
                    "jobgrad": {
                        (1, 2): ("master_1", False),
                        (3, 1): ("master_3", False),
                        (1, 1): ("grad_1_1", True),
                        (1, 3): ("grad_1_3", False),
                        (3, 2): ("grad_3_2", False),
                    },
                    "densjob": {},
                    "rootstate": 2,
                },
                "molecule": {
                    "comment": "\n",
                    "natom": 3,
                    "elements": ["S", "O", "O"],
                    "unit": "angstrom",
                    "factor": 1.8897261246257702,
                    "states": [3, 0, 2],
                    "nstates": 5,
                    "nmstates": 9,
                    "point_charges": False,
                    "npc": 0,
                    "Atomcharge": 32,
                    "frozcore": 7,
                },
                "resources": {
                    "pwd": os.getcwd(),
                    "cwd": os.getcwd(),
                    "scratchdir": os.path.join(os.getcwd(), "SCRATCH"),
                    "ncpu": 1,
                    "ngpu": None,
                    "memory": 2000,
                    "delay": 0.0,
                    "theodir": None,
                    "theodore_prop": [],
                    "theodore_fragment": [],
                    "wfoverlap": "$SHARC/wfoverlap.x",
                    "wfthres": 0.998,
                    "resp_shells": [],
                    "resp_vdw_radii_symbol": {},
                    "resp_vdw_radii": [],
                    "resp_betas": [0.0005, 0.0015, 0.003],
                    "resp_layers": 4,
                    "resp_first_layer": 1.4,
                    "resp_density": 10.0,
                    "resp_fit_order": 2,
                    "resp_mk_radii": True,
                    "resp_grid": "lebedev",
                    "groot": None,
                    "numfrozcore": 0,
                    "wfnumocc": None,
                    "schedule_scaling": 0.9,
                    "neglected_gradient": "zero",
                    "dry_run": False,
                    "debug": False,
                    "min_cpu": 1,
                },
                "maps": {
                    "statemap": {
                        1: [1, 1, 0.0],
                        2: [1, 2, 0.0],
                        3: [1, 3, 0.0],
                        4: [3, 1, -1.0],
                        5: [3, 2, -1.0],
                        6: [3, 1, 0.0],
                        7: [3, 2, 0.0],
                        8: [3, 1, 1.0],
                        9: [3, 2, 1.0],
                    },
                    "mults": None,
                    "gsmap": {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
                    "gradmap": {(3, 2)},
                    "nacmap": None,
                    "densmap": None,
                    "ionmap": None,
                    "chargemap": {1: 0, 2: 1, 3: 0},
                    "multmap": {1: 1, -1: [1], 3: 3, -3: [1, 3]},
                },
            },
        },
    ]

    for ij, (job_ref, job) in enumerate(zip(ref_schedule, gaussian.QMin.scheduling["schedule"])):
        for key in job_ref.keys():
            for subk in ["control", "molecule", "resources", "maps"]:
                for k, v in job_ref[key][subk].items():
                    if k not in job[key][subk].data:
                        raise KeyError(f"{k} not in schedule[{ij}][{subk}]")
                    if f"{v}" != f"{job[key][subk][k]}":
                        raise ValueError(f"schedule[{ij}][{subk}][{k}] should be {v} not {job[key][subk][k]}")
