name: sharc4.1_compat
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.2
  - scipy=1.15
  - h5py
  - matplotlib
  - pyparsing
  - netcdf4
  - gfortran_linux-64
  - pyscf
  - openmm
  - numba
  - sympy
  - pyyaml
  - pytorch
  - pytest
  - ase
  - opt_einsum
  - threadpoolctl
  - pip
  - joblib

